main: me.mathmaniac43.efficiencyexpert.EfficiencyExpert
name: EfficiencyExpert
author: mathmaniac43
version: 1.0

commands:
    ee:
        aliases: [efficiencyexpert, efex]

permissions:
    efficiencyexpert.*:
        description: Gives player access to entirety of EfficiencyExpert plugin.
        default: op